version: '3.4'
services:
  web:
    build: .
    container_name: debug_vs
    ports:
      - "8080:80"
      - "4022:4022"
    volumes:
      - C:\Presentations\docker_temp\debug_vs\web\Web\bin\Release\Publish:C:\inetpub\wwwroot\app
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    
networks:
 default:
  external:
   name: "nat"